### ISSUE TITLE
Kibana is currently running with legacy OpenSSL providers enabled!

### ISSUE THREAD

**Issue by alestanga** [arktronic/docker-quick-elastic-netflow#1]
hello.
I've built you docker container but it doesn't start.
it complains about a "multiline key may not be an implicit key at line 6"
anyway, inside the container, the kibana.yml file contains these lines:
Kibana is currently running with legacy OpenSSL providers enabled!

and the instructions on how to disable the legacy OpenSSL providers.
I've tried to run the "/usr/share/kibana/bin/kibana-encryption-keys generate -q" command inside the containers and it spawns this error.
so when the launch-kibana.sh script is called it appends the error to the kibana.yml file and the file becomes unusable.
maybe, could you please disable the OpenSSL providers in the node.options file?
thank you.

**Comment by arktronic** [comment]
Huh, looks like they introduced some incompatibility in v7.17.13. I'll take a look. Thanks for the report!

**Comment by arktronic** [comment]
Please try it now.

**Comment by alestanga** [comment]
thank you! 
now it works.
